import './globals.css';

import localFont from 'next/font/local';

const myFont = localFont({
  src: './SUIT-Variable.woff2',
  display: 'swap',
  variable: '--font-suit',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ko' className={`${myFont.variable}`}>
      <body>
        <div className='min-h-screen text-white100'>{children}</div>
      </body>
    </html>
  );
}
